export const FETCH_CARDS = 'flashcard/card/fetch'
export const ADD_CARD = 'flashcard/card/add'
export const EDIT_CARD = 'flashcard/card/edit'
export const TOGGLE_KNOWN_UNKNOWN = 'flashcard/card/toggle'
export const DELETE_CARD = 'flashcard/card/delete'
